### PR TITLE
Add Probabilistic to GPUStreamlines

### PR DESCRIPTION
**Pull request by 36000**
Done:
  -> Adds model agnostic probabilistic option
  -> Adds first draft of a model agnostic PTT option 
  -> Handle c vs fortran order for all inputs, not just dataf
  -> Moves all the run*.py files into one so I only had to make changes in one place (If there is a reason this was in four files, I can put it back)

### CODE REVIEW

**Comment by arokem** [comment]
Hey @36000 : any reason not to merge this now?

**Comment by 36000** [comment]
I will merge

**Comment by arokem** [comment]
Should we merge to master?

**Comment by arokem** [comment]
I created #18 to advance merging this into the master branch.

**Pull request merged**
